#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../../autoload.php')) {
    require __DIR__.'/../../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Lwwcas\Holo\Commands\Install\GitInstall);
$application->add(new Lwwcas\Holo\Commands\Install\VsCodeInstall);
$application->add(new Lwwcas\Holo\Commands\Install\GoogleChromeInstall);

$application->add(new Lwwcas\Holo\Commands\VsCode\VsCodeBuilder);
$application->add(new Lwwcas\Holo\Commands\VsCode\VsCodeFont);
$application->add(new Lwwcas\Holo\Commands\VsCode\VsCodeExtensions);
$application->add(new Lwwcas\Holo\Commands\VsCode\VsCodeConfig);

$application->run();
