#!/usr/bin/env php
<?php

require '/home/lucas/vendor/autoload.php';
//if (file_exists(__DIR__.'/../../../autoload.php')) {
//    require __DIR__.'/../../../autoload.php';
//} else {
//    require __DIR__.'/vendor/autoload.php';
//}

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Lwwcas\Holo\Commands\GitInstall);

$application->add(new Lwwcas\Holo\Commands\VsCodeInstall);
$application->add(new Lwwcas\Holo\Commands\VsCodeBuilder);

$application->run();
